### ISSUE TITLE
Update Full Node flags/options

### ISSUE THREAD

**Issue by timbrinded** [moonbeam-foundation/moonbeam-docs#635]
The pages for [Run a Node on Moonbeam Using Systemd
](https://docs.moonbeam.network/node-operators/networks/run-a-node/systemd/) and [Run a Node on Moonbeam Using Docker](https://docs.moonbeam.network/node-operators/networks/run-a-node/docker/) should be updated with the latest recommended options.

- `--execution wasm` is default, doesn't need to be explicitly set
- `--wasm-execution compiled` is default, doesn't need to be explicitly set
- `--trie-cache-size 0` might want to double check if this is still the recommendation for collators as i thought cache is meant to improve performance not degrade.
- `--sync <strategy>` Depending on whether we think these instructions are intended for people wanting to run full nodes for RPC reasons - or builder teams for their own infra, we should probably encourage them to use the quicker sync methods.

**Comment by eshaben** [comment]
thanks @timbrinded !

**Comment by eshaben** [comment]
Feedback has been applied and published to the docs site! Thanks again! 🙌
