### ISSUE TITLE
[Feedback] Deploy Contracts with Truffle - /builders/build/eth-api/dev-env/truffle/

### ISSUE THREAD

**Issue by CasiniNift** [moonbeam-foundation/moonbeam-docs#662]
When I run this command on my terminal "truffle migrate --network dev" I get this error Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)

**Comment by eshaben** [comment]
hey! thanks for reporting. you're getting this error in your terminal directly after running the command? or in your development node logs?

I just tried using this command on the example contract, `MyToken.sol`, in the [moonbeam truffle box](https://github.com/PureStake/moonbeam-truffle-box) with truffle version v5.8.2 and was unable to reproduce the issue.

what version of truffle are you running? it might help to try installing the latest version of truffle and seeing if that does the trick.

if that doesn't work, could you please provide reproduction steps? that would be super helpful! thanks! 🙂

**Comment by CasiniNift** [comment]
Sorry for the late reply 
I am getting this error directly in the terminal 

What is the lateste version of truffle ? That way I can make sure that it's installed

**Comment by eshaben** [comment]
> What is the lateste version of truffle ? That way I can make sure that it's installed

It is 5.9.0. Just so you know, you can always find the latest version on the npm page for the package where it says version: https://www.npmjs.com/package/truffle

**Comment by eshaben** [comment]
@CasiniNift ok. I'm not able to reproduce the issue, so we can kind of start by going down the list to narrow it down:

- are you on linux, mac, or windows?
- how did you start up the development node? can you please share the exact command?
- when did the error occur? were you trying to interact with the node or did it randomly start appearing? 
- if you were trying to interact with the node, what were you trying to do?

another idea that would certainly help is to restart your node as that generally helps with node-related issues. if you use the moonbeam truffle box and plugin to start up the node, you can simple run:

```
truffle run moonbeam stop && \
truffle run moonbeam remove
```

If you used Docker, you can take the following steps:

1. run `docker container ls` to get a list of your containers
2. find the `purestake/moonbeam` container and grab the container ID
3. run `docker stop CONTAINER_ID && docker rm CONTAINER_ID` (just replace `CONTAINER_ID` with the actual ID of the container) 

This will stop the container, then you can start the node back up using the command you originally started it up with. There are directions on the [Moonbeam Development Node](https://docs.moonbeam.network/builders/get-started/networks/moonbeam-dev/#spin-up-a-node) page of our docs site, just in case.

**Comment by CasiniNift** [comment]
I was able to make it work.
Thank you for the help.
